enum TicketClass
{
    Ticket          = 9
    Incident        = 32
    MajorIncident   = 77
    Problem         = 33
    Change          = 34
    Release         = 35
    TicketTemplate  = 36
    ServiceRequest  = 46
}

enum TicketStatus
{
    AwaitingClientResponse = 19861
    Cancelled              = 12206
    Closed                 = 12205
    InProcess              = 12203
    OnHold                 = 12207
    Open                   = 12202
    Reopened               = 15436
    Resolved               = 12204
    TicketEscalated        = 47191
}

enum StatusClass
{
    None      = 0
    New       = 1
    InProcess = 2
    Completed = 3
    Cancelled = 4
    OnHold    = 5
    Requested = 6
}

enum TicketSource
{
    AutoGenerated          = 1009
    Chat                   = 1280
    ClientPortal           = 927
    Email                  = 929
    ITInternal             = 1121
    Phone                  = 928
    WalkUp                 = 1010
    WalkUpBell525          = 1950
    WalkUpEducationCenter  = 1951
    WalkUpFieldTechnicians = 1953
    WalkUpLibrary          = 1952
}

enum TicketImpact
{
    AffectsUser         = 2923
    AffectsGroup        = 2924
    AffectsDepartment   = 2925
    AffectsOrganization = 2926
}

enum TicketPriority
{
    Standard                = 2930
    Medium                  = 2931
    High                    = 2932
    Emergency               = 2933
    CapitalEfficienies      = 4041
    Compliance              = 4042
    Security                = 4042
    Assurance               = 4042
    RiskManagement          = 4042
    CoreDifferentiator      = 4043
    FacilityImprovement     = 4044
    Fiscal                  = 4045
    Mandate                 = 4046
    OperationalEfficiencies = 4047
    Strategic               = 4048
    TeachingLearning        = 4049
}

enum TicketUrgency
{
    Low     = 2927
    Medium  = 2928
    High    = 2929
}

enum FirstContactResolution
{
    Yes = 63741
    No  = 63742
}